---
- name: Deploy Monitor on OpenStack
  hosts: localhost
  gather_facts: false
  roles:
    - launch_monitor

- name: Provision monitor
  hosts: monitor
  user: ubuntu
  become: true
  gather_facts: false
  tasks:
    - name: Install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Install python and support packages
      apt: name={{item}} state=present
      with_items:
      - python-simplejson
      - python-pip

# - name: Provision monitor
#   hosts: monitor
#   user: ubuntu
#   become: true
#   gather_facts: false
#   roles:
#     - provision_monitor
