---
- name: Deploy monitor
  hosts: localhost
  gather_facts: false
  roles:
    - deploy_monitor

- name: Deploy webserver
  hosts: localhost
  gather_facts: false
  roles:
    - deploy_webserver

- name: Deploy api-gateway
  hosts: localhost
  gather_facts: false
  roles:
    - deploy_apigateway

- name: Deploy service_a
  hosts: localhost
  gather_facts: false
  roles:
    - deploy_service_a

- name: Deploy service_b
  hosts: localhost
  gather_facts: false
  roles:
    - deploy_service_b

- name: Deploy database_a
  hosts: localhost
  gather_facts: false
  roles:
    - deploy_database_a

- name: Deploy database_b
  hosts: localhost
  gather_facts: false
  roles:
    - deploy_database_b
