---
- name: create instances
  hosts: localhost
  roles:
    - create_swarm_inst

- name: Provision nodes
  hosts: sw_test
  user: ubuntu
  become: true
  gather_facts: false
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Download docker sh
      get_url:
        url: https://get.docker.com/
        dest: /home/ubuntu/get-docker.sh

    - name: Change the working directory to somedir/ before executing the command.
      shell: .  get-docker.sh
      args:
        chdir: /home/ubuntu/

- name: Initiate manager
  hosts: sw_test_manager
  user: ubuntu
  become: true
  gather_facts: false
  tasks:
  - name: init swarm
    shell: docker swarm init

  - name: get token 
    shell: docker swarm join-token -q manager
    register: token  
        
- name: Add nodes to swarm
  hosts: sw_test
  user: ubuntu
  become: true
  gather_facts: false
  tasks:
    - name: add nodes
      shell: docker swarm join --token {{token}} 192.168.20.67:2377
  

    