---
# Step 1, from local machine
- import_playbook: deploy_network.yml
- import_playbook: deploy_controlmachine.yml
- import_playbook: provision_controlmachine.yml

# Step 2, from controlmachine
- import_playbook: deploy_monitormachine.yml
- import_playbook: deploy_webclient.yml
- import_playbook: deploy_recipemanager.yml
- import_playbook: deploy_recipeworkers.yml
- import_playbook: deploy_beermanager.yml
- import_playbook: deploy_beerworkers.yml
- import_playbook: deploy_apimanager.yml
- import_playbook: deploy_apiworkers.yml

# Step 3
# Manually compose inventory file './hosts'

# Step 4, from controlmachine using inventory file, '-i ./hosts'
- import_playbook: provision_monitormachine.yml
- import_playbook: provision_webclient.yml
- import_playbook: provision_recipemanager.yml
- import_playbook: provision_recipeworkers.yml
- import_playbook: provision_beermanager.yml
- import_playbook: provision_beerworkers.yml
- import_playbook: provision_apimanager.yml
- import_playbook: provision_apiworkers.yml
