---
- name: create instances
  hosts: localhost
  roles:
    - create_instances

#- name: Provision nodes
#  hosts: os_hosts
#  user: ubuntu
#  become: true
#  gather_facts: false
#  vars:
#    source_key: /home/popniten/LNU/config-2dv514/Grupp02-examination-ht17/vault/2dv514-temp
#    dest_key: /home/ubuntu/.ssh/2dv514-temp
#  tasks:
#    - name: install python 2
#      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
#
#    - name: ensure repository key is installed
#      apt_key:
#        id: "58118E89F3A912897C070ADBF76221572C52609D"
#        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
#        state: present
#
#    - name: ensure docker registry is available
#      # For Ubuntu 14.04 LTS, use this repository:
#      # apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
#      # For Ubuntu 16.04 LTS, use this repo instead:
#      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present
#
#    - name: ensure docker and dependencies are installed
#      apt: name=docker-engine update_cache=yes
#
#    - service: name=docker state=restarted
#    
#    - name: Copy docker-compose
#      copy:
#        src: api/
#        dest: '/home/ubuntu/api'
#        owner: ubuntu
#        group: ubuntu    
