---
- name: Deploy database-a
  os_server:
    state: present
    name: acme_database-a
    image: Ubuntu server 16.04
    key_name: "{{ keyname }}"
    wait: yes
    flavor: "{{ default_flavor }}"
    auto_floating_ip: no
    network: "{{ companyname }}_LAN"
    security_groups:
      - ssh
    meta:
      hostname: acme_database-a.localdomain
  register: acme_database-a

- name: Add VM to inventory
  add_host:
    name: acme_database-a
    hostname: "{{acme_database-a.server.public_v4}}"
    ansible_host: "{{acme_database-a.server.public_v4}}"
