version: "3"
services:
    beers:
        image: fredriko83/beerapi
        ports:
            - "8000:80"
        depends_on:
            - beers_db
        networks:
            - beers
    beers_db:
        image: "microsoft/mssql-server-linux:2017-latest"
        environment:
            SA_PASSWORD: "Supersecret1234"
            ACCEPT_EULA: "Y"
        networks:
            - beers
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "8080:8080"
        stop_grace_period: 1m30s
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]       
networks:
  beers: