---
- name: Deploy webclient machine
  os_server:
    state: present
    name: webclient
    image: Ubuntu server 16.04
    key_name: 2dv514-g2-key
    wait: yes
    flavor: cpu1-ram1024-disk10
    auto_floating_ip: yes
    network: Acme_LAN
    security_groups:
      - default
      - ssh
      - http
    meta:
      hostname: webclient.localdomain
  register: webclient

# - debug: msg="hostvars={{hostvars}}"

- name: Add VM to inventory
  add_host:
    name: webclient
    hostname: "{{webclient.server.public_v4}}"
    ansible_host: "{{webclient.server.public_v4}}"

- name: Wait for SSH to be ready
  pause:
    seconds: 60

# - debug: msg="webclient={{webclient}}"

# - name: Add IP address of all hosts to all hosts
#   lineinfile:
#     owner: ubuntu
#     group: ubuntu
#     dest: /etc/ansible/hosts
#     line: "webclient ansible_host={{ webclient.server.private_v4 }}"
#     state: present
