---
    - name: launch instances
      os_server:
        name: "{{ prefix }}-{{ item.name }}"
        state: present
        key_name: "{{ item.key }}"
        image: "{{ item.image }}"
        flavor: "{{ item.flavor }}"
        network: Acme_LAN
        security_groups:
          - ssh
          - swarm
      with_items: "{{ servers }}"
      register: "os_hosts"