---
    - name: launch instances
      os_server:
        name: "{{ prefix }}-{{ item.name }}"
        state: present
        key_name: "{{ item.key }}"
        image: "{{ item.image }}"
        flavor: "{{ item.flavor }}"
        network: Acme_LAN
        security_groups:
          - ssh
          - swarm
      with_items: "{{ servers }}"
      register: "os_hosts"


    - name: add hosts to inventory
      add_host:
        name: "{{ item['item'].name }}"
        groups: "{{ item['item']['meta']['group'] }}"
        ansible_host: "{{ item.openstack.accessIPv4 }}"
      with_items: "{{ os_hosts.results }}"

    - name: Provision nodes
      user: ubuntu
      become: true
      gather_facts: false
      tasks:
        - name: install python 2
          raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

        - name: Download docker sh
          get_url:
            url: https://get.docker.com/
            dest: /home/ubuntu/get-docker.sh

        - name: Install docker
          shell: .  get-docker.sh
          args:
            chdir: /home/ubuntu
        with_items: "{{ os_hosts.results }}"    