---
- name: Create SSH security group
  os_security_group:
    state: present
    name: ssh
    description: SSH Security Group

- name: Update SSH rule
  os_security_group_rule:
    security_group: ssh
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

- name: Create http security group
  os_security_group:
    state: present
    name: http
    description: http Security Group

- name: Update http rule
  os_security_group_rule:
    security_group: http
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

- name: Create monitor security group
  os_security_group:
    state: present
    name: monitor
    description: monitor Security Group

- name: Update monitor rule
  os_security_group_rule:
    security_group: monitor
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0

- name: Create swarm security group
  os_security_group:
    state: present
    name: swarm
    description: swarm Security Group

- name: Update swarm rule
  os_security_group_rule:
    security_group: swarm
    protocol: tcp
    port_range_min: 2377
    port_range_max: 2377
    remote_ip_prefix: 0.0.0.0/0

- name: Create local area network
  os_network:
    name: "{{ companyname }}_LAN"
    state: present

- name: Create subnet
  os_subnet:
    name: "{{ companyname }}_Subnet"
    state: present
    network_name: "{{ companyname }}_LAN"
    dns_nameservers:
      - 194.47.199.41
      - 194.47.110.97
    cidr: 192.168.20.0/24
    allocation_pool_start: 192.168.20.50
    allocation_pool_end: 192.168.20.99

- name: Create router
  os_router:
    name: "{{ companyname }}_Router"
    state: present
    network: "{{ externalnetwork }}"
    interfaces:
      - "{{ companyname }}_Subnet"
