---
- name: Deploy api-gateway
  os_server:
    state: present
    name: acme_api-gateway
    image: Ubuntu server 16.04
    key_name: "{{ keyname }}"
    wait: yes
    flavor: "{{ default_flavor }}"
    auto_floating_ip: yes
    network: "{{ companyname }}_LAN"
    security_groups:
      - ssh
      - webservice
    meta:
      hostname: acme_api-gateway.localdomain
  register: acme_api-gateway

- name: Add VM to inventory
  add_host:
    name: acme_api-gateway
    hostname: "{{acme_api-gateway.server.public_v4}}"
    ansible_host: "{{acme_api-gateway.server.public_v4}}"

