---
- name: Create SSH security group
  os_security_group:
    state: present
    name: ssh
    description: SSH Security Group

- name: Update SSH rule
  os_security_group_rule:
    security_group: ssh
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

- name: Create webservice security group
  os_security_group:
    state: present
    name: webservice
    description: webservice Security Group

- name: Update webservice rule
  os_security_group_rule:
    security_group: webservice
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

- name: Update webservice rule
  os_security_group_rule:
    security_group: webservice
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0

- name: Update webservice rule
  os_security_group_rule:
    security_group: webservice
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0

- name: Update webservice rule
  os_security_group_rule:
    security_group: webservice
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0

- name: Create local area network
  os_network:
    name: "{{ companyname }}_LAN"
    state: present

- name: Create subnet
  os_subnet:
    name: "{{ companyname }}_Subnet"
    state: present
    network_name: "{{ companyname }}_LAN"
    dns_nameservers:
      - 194.47.199.41
      - 194.47.110.97
    cidr: "{{ network_pool }}.0/24"
    allocation_pool_start: "{{ network_pool }}.50"
    allocation_pool_end: "{{ network_pool }}.99"

- name: Create router
  os_router:
    name: "{{ companyname }}_Router"
    state: present
    network: "{{ externalnetwork }}"
    interfaces:
      - "{{ companyname }}_Subnet"
