---
- name: Deploy controlmachine on OpenStack
  hosts: localhost
  gather_facts: false
  roles:
    - launch_controlmachine

- name: Provision controlmachine
  hosts: controlmachine
  user: ubuntu
  become: true
  gather_facts: false
  tasks:
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: Adding Ansible repository
      apt_repository: repo="ppa:ansible/ansible"

    - name: Install Ansible and support packages
      apt: name={{item}} state=present
      with_items:
      - python-pip
      - python-software-properties
      - ansible
      - gcc
      - python-dev
      - libffi-dev
      - libssl-dev
      - sqlite3
      - libsqlite3-dev
      - git

    - name: Install OpenStack client
      pip:
        name: python-openstackclient

    - name: Install Shade
      pip:
        name: shade

    - name: ensure repository key is installed
      apt_key:
        id: "58118E89F3A912897C070ADBF76221572C52609D"
        keyserver: "hkp://p80.pool.sks-keyservers.net:80"
        state: present

    - name: ensure docker registry is available
      # For Ubuntu 14.04 LTS, use this repository:
      # apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
      # For Ubuntu 16.04 LTS, use this repo instead:
      apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-xenial main' state=present

    - name: ensure docker and dependencies are installed
      apt: name=docker-engine update_cache=yes

    - service: name=docker state=restarted

    - name: Ensure git repo exists.
      git:
        repo: https://github.com/Popniten/2dv514-ansible-deployment.git
        dest: /home/ubuntu/playbooks
      owner: ubuntu
