---
- name: Deploy monitoring machine
  os_server:
    state: present
    name: acme_monitor
    image: Ubuntu server 16.04
    key_name: "{{ keyname }}"
    wait: yes
    flavor: "{{ default_flavor }}"
    auto_floating_ip: yes
    network: "{{ companyname }}_LAN"
    security_groups:
      - ssh
      - webservice
    meta:
      hostname: acme_monitor.localdomain
  register: acme_monitor

- name: Add VM to inventory
  add_host:
    name: acme_monitor
    hostname: "{{acme_monitor.server.public_v4}}"
    ansible_host: "{{acme_monitor.server.public_v4}}"
