version: '3'
volumes:
  dbdata:

services:
  web:
    image: andrasballa/recipeapi_web
    # build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
      - ./database:/tmp/database
    command: mysqld --init-file="/tmp/database/schema.sql"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=2DV514
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"