version: '3.1'
volumes:
  dbdata:

services:
  web:
    image: andrasballa/recipeapi_web
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      recipes
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
      - /home/ubuntu/api/database:/docker-entrypoint-initdb.d
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=2DV514
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    networks:
      recipes
networks:
  recipes: