--- 
# tasks file for nodejs  

  - name: Get script
    get_url:
      url: "http://deb.nodesource.com/setup_6.x"
      dest: "{{homeDir}}/nodejs.sh"

  - name: Set execution right to script
    file:
      path: "{{homeDir}}/nodejs.sh"
      mode: "u+x"

  - name: Execute installation script
    shell: "{{homeDir}}/nodejs.sh"        

  - name: Install Packages
    apt: 
      name={{ item }}
      update_cache=yes
      state=latest
    with_items:
      - build-essential
      - nodejs
      - git
      - curl

  - name: Install pm2
    npm: 
      name=pm2
      global=yes
      production=yes    

  - name: Git Clone Repo
    git: 
      repo=https://github.com/{{account}}/{{repo}}.git
      dest={{homeDir}}/{{appDir}}
    register: git_finished

  - name: Running NPM install
    npm: 
      path={{homeDir}}/{{appDir}}
    register: npm_finished
    when: git_finished.changed

  - name: ensure file exists
    copy:
      content: ""
      dest: "{{homeDir}}/{{appDir}}/.env"
      force: no
      group: root
      owner: root
      mode: 0555

  - name: Add mail to .env
    lineinfile:
      owner: root
      group: root
      dest: /home/ubuntu/app/.env
      line: "MAIL_USER={{mail}}"
      state: present

  - name: Add smtp to .env
    lineinfile:
      owner: root
      group: root
      dest: /home/ubuntu/app/.env
      line: "MAIL_SMTP={{mailsmtp}}"
      state: present

  - name: Add mail pass to .env
    lineinfile:
      owner: root
      group: root
      dest: /home/ubuntu/app/.env
      line: "MAIL_PASSWORD={{mailpass}}"
      state: present

  - name: Add uri to .env
    lineinfile:
      owner: root
      group: root
      dest: /home/ubuntu/app/.env
      line: "DB_URI={{db}}"
      state: present
  
  - name: reload .profile
      become_user: ubuntu
      shell: . ~/.profile
    # ignore_errors: yes

  #- name: set ownership
  #  command: chown -R ubuntu app chdir={{homeDir}}

  - name: Fix 'app' permissions
    file:
      path={{homeDir}}/{{appDir}}
      owner=ubuntu
      group=ubuntu
      mode=0775
      state=directory
      recurse=yes

  - name: Stop monitor
    become_user: ubuntu
    shell: pm2 delete monitor chdir={{homeDir}}/{{appDir}}
    ignore_errors: yes

  - name: Start monitor
    become_user: ubuntu
    shell: pm2 start -x -i 1 index.js --name monitor chdir={{homeDir}}/{{appDir}}
    ignore_errors: yes
   # when: npm_finished.changed
