---
- name: Deploy control machine
  os_server:
    state: present
    name: acme_controller
    image: Ubuntu server 16.04
    key_name: "{{ keyname }}"
    wait: yes
    flavor: "{{ default_flavor }}"
    auto_floating_ip: yes
    network: "{{ companyname }}_LAN"
    security_groups:
      - ssh
    meta:
      hostname: acme_controller.localdomain
  register: acme_controller

- name: Add VM to inventory
  add_host:
    name: acme_controller
    hostname: "{{acme_controller.server.public_v4}}"
    ansible_host: "{{acme_controller.server.public_v4}}"

- name: Wait for SSH to be ready
  pause:
    seconds: 60
