version: '3'
volumes:
  dbdata:
  mssql-server-linux-data:
networks:
  recipes:
  backend:
  beers_network:
  frontend:

#Default Gateway
services: 
  api:
    image: wallstedt/api-aggregator:latest
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - servicedb
    links:
      - web
    networks:
      - frontend
      - recipes
      - backend
      - beers_network
  
  #Beer API
  beers:
    image: fredriko83/beerapi:latest
    depends_on:
      - beers_db
    networks: 
      - beers_network

  #Beer Database
  beers_db:
    image: microsoft/mssql-server-linux:2017-latest
    environment: 
      SA_PASSWORD: "Supersecret1234"
      ACCEPT_EULA: "Y"
    networks: 
      - beers_network
    volumes:
      - mssql-server-linux-data:/var/opt/mssql/data

  #Default Gateway Database
  servicedb:
    image: mongo
    networks:
      - backend
    volumes:
      - /data/db
  
  #Recipe API
  web:
    image: andrasballa/recipeapi_web
    depends_on:
      - db
    networks: 
      - recipes

  #Recipe Database    
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=2DV514
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    networks:
      - recipes

  #Nginx Network Proxy    
  rp:
    image: wallstedt/minimal-proxy
    ports: 
      - "8001:8001"
    restart: always
    networks: 
      - frontend